name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
      - uses: actions/checkout@v1
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
          
      - name: npm install, build and test
        run: |
          yarn
          npm run build --if-present
          npm test
